# Generated by Django 5.1.7 on 2025-03-29 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='remind_time',
            field=models.DateTimeField(),
        ),
    ]
